version: '3'

services:

  postgres_auth:
    container_name: postgres_auth
    image: postgres
    env_file:
      - ./apps/auth/.auth.env
    ports:
      - '5434:5432'
    volumes:
      - ./db/auth-db:/var/lib/postgresql/data

  postgres_profile:
    container_name: postgres_profile
    image: postgres
    env_file:
      - ./apps/profile/.profile.env
    ports:
      - '5433:5432'
    volumes:
      - ./db/profile-db:/var/lib/postgresql/data

  postgres_admin:
    container_name: pgadmin
    image: dpage/pgadmin4
    depends_on:
      - postgres_auth
      - postgres_profile
    env_file:
      - .env
    ports:
      - '15432:80'
    volumes:
      - ./db/pgadmin:/var/lib/data

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    depends_on:
      - postgres_auth
      - postgres_profile
    volumes:
      - /var/lib/rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    env_file:
      - .env

  auth:
    container_name: auth
    build:
      context: ./
      dockerfile: ./apps/auth/Dockerfile
    env_file:
      - ./apps/auth/.auth.env
    depends_on:
      - rabbitmq
      - postgres_auth
      - profile
    links:
      - postgres_auth
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3100:3100'
    command: npm run start:dev auth

  profile:
    container_name: profile
    build:
      context: ./
      dockerfile: ./apps/profile/Dockerfile
    env_file:
      - ./apps/profile/.profile.env
    depends_on:
      - rabbitmq
      - postgres_profile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    links:
      - postgres_profile
    ports:
      - '3200:3200'
    command: npm run start:dev profile

  api:
    container_name: api
    build:
      context: ./
      dockerfile: ./apps/api/Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - auth
      - profile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev api
